<script lang="ts">
  import { Icon } from '@horizon/icons'
  import type { WebviewError } from './Webview.svelte'
  import { createEventDispatcher } from 'svelte'

  export let error: WebviewError

  const dispatch = createEventDispatcher<{ reload: void }>()

  const prettyErrors = {
    // TODO: these have been generated by Copilot and need to be reviewed and possibly updated
    ERR_NAME_NOT_RESOLVED: {
      title: 'This website is not reachable',
      description: 'The site could not be found. Please check the URL and try again.'
    },
    ERR_CONNECTION_REFUSED: {
      title: 'Website refused to connect',
      description: 'The site is not reachable. Please check the URL and try again.'
    },
    ERR_CONNECTION_TIMED_OUT: {
      title: 'Website took too long to respond',
      description:
        'The site took too long to respond. Please check your internet connection and try again.'
    },
    ERR_INTERNET_DISCONNECTED: {
      title: 'No internet connection',
      description: 'The site is not reachable. Please check your internet connection and try again.'
    },
    ERR_NAME_RESOLUTION_FAILED: {
      title: 'This website is not reachable',
      description: 'The site could not be found. Please check the URL and try again.'
    },
    ERR_SSL_PROTOCOL_ERROR: {
      title: 'This website is not reachable',
      description:
        'The site could not be reached due to an SSL error. Please check the URL and try again.'
    },
    ERR_ADDRESS_UNREACHABLE: {
      title: 'This website is not reachable',
      description: 'The site could not be reached. Please check the URL and try again.'
    },
    ERR_CONNECTION_CLOSED: {
      title: 'Website connection closed',
      description: 'The site connection was closed. Please check the URL and try again.'
    },
    ERR_CONNECTION_RESET: {
      title: 'Website connection reset',
      description: 'The site connection was reset. Please check the URL and try again.'
    },
    ERR_EMPTY_RESPONSE: {
      title: 'Website returned an empty response',
      description: 'The site returned an empty response. Please check the URL and try again.'
    },
    ERR_FAILED: {
      title: 'Website failed to load',
      description: 'The site failed to load. Please check the URL and try again.'
    },
    ERR_FILE_NOT_FOUND: {
      title: 'File not found',
      description: 'The file could not be found. Please check the URL and try again.'
    },
    ERR_ABORTED: {
      title: 'Website connection aborted',
      description: 'The site connection was aborted. Please check the URL and try again.'
    },
    ERR_INSECURE_RESPONSE: {
      title: 'Insecure response',
      description: 'The site returned an insecure response. Please check the URL and try again.'
    },
    ERR_INVALID_URL: {
      title: 'Invalid URL',
      description: 'The URL is invalid. Please check the URL and try again.'
    },
    ERR_UNKNOWN_URL_SCHEME: {
      title: 'Unknown URL scheme',
      description: 'The URL scheme is unknown. Please check the URL and try again.'
    },
    ERR_BLOCKED_BY_CLIENT: {
      title: 'Website blocked by client',
      description:
        'The site was blocked by the client. Please check the URL and try disabling any ad blockers or security software.'
    }
  } as any

  $: prettyError = prettyErrors[error.description] || {
    title: 'Failed to load website',
    description: 'An error occurred while trying to load the page.'
  }

  function handleReload() {
    dispatch('reload')
  }
</script>

<div class="wrapper">
  <div class="content">
    <Icon name="alert-triangle" size="40px" />
    <h1>{prettyError.title}</h1>

    <div class="inner">
      <p>{prettyError.description}</p>
      <a href={error.url}>{error.url}</a>
    </div>

    <p class="code">{error.description} ({error.code})</p>

    <button on:click={handleReload}> Reload Page </button>
  </div>
</div>

<style lang="scss">
  .wrapper {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: #fff;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .content {
    display: flex;
    flex-direction: column;
    gap: 2rem;
    width: 600px;
    max-width: 90%;

    h1 {
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--color-text);
    }

    p {
      font-size: 1.1rem;
      color: var(--color-text-muted);
    }

    a {
      font-size: 1.1rem;
      color: rgb(66, 93, 243);
      text-decoration: none;
      transition: color 0.2s;

      &:hover {
        color: var(--color-link-dark);
      }
    }

    button {
      padding: 0.5rem 1rem;
      border: none;
      outline: none;
      border-radius: 8px;
      background: #f73b95;
      color: #fff;
      cursor: pointer;
      transition: color 0.2s;
      font-size: 1.1rem;
      width: fit-content;

      &:hover {
        background: #f92d90;
      }

      &:active {
        transform: scale(0.95);
      }
    }

    .code {
      font-size: 1.1rem;
      font-family: monospace;
      opacity: 0.5;
    }
  }

  .inner {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
</style>
