use crate::store::models::*;

pub enum WorkerMessage {
    CreateCard(Card),
    CreateHistoryEntry(HistoryEntry),
    CreateHorizon(String),
    CreateResource {
        resource_type: String,
        resource_tags: Option<Vec<ResourceTag>>,
        resource_metadata: Option<ResourceMetadata>,
    },
    CreateUserdata(String),
    DeleteHistoryEntry(String),
    DeleteResource(String),
    GetAllHistoryEntries,
    GetCard(String),
    GetHistoryEntry(String),
    GetUserdataByUserId(String),
    ListCardsInHorizon(String),
    ListHorizons(),
    PostProcessJob(String),
    Print(String),
    ReadResource(String),
    RecoverResource(String),
    RemoveCard(String),
    RemoveHorizon(String),
    RemoveUserdata(String),
    SearchResources {
        query: String,
        resource_tags: Option<Vec<ResourceTag>>,
    },
    UpdateCardData(String, Vec<u8>),
    UpdateCardDimensions(String, i64, i64, i32, i32),
    UpdateCardResourceID(String, String),
    UpdateCardStackingOrder(String),
    UpdateHistoryEntry(HistoryEntry),
    UpdateHorizon(Horizon),
}
