use crate::store::models::*;

pub enum WorkerMessage {
    CreateCard(Card),
    CreateHistoryEntry(HistoryEntry),
    CreateHorizon(String),
    CreateResource {
        resource_type: String,
        resource_tags: Option<Vec<ResourceTag>>,
        resource_metadata: Option<ResourceMetadata>,
    },
    CreateResourceTag(ResourceTag),
    CreateUserdata(String),
    GetAllHistoryEntries,
    GetCard(String),
    GetHistoryEntry(String),
    GetResource(String),
    GetUserdataByUserId(String),
    ListCardsInHorizon(String),
    ListHorizons(),
    PostProcessJob(String),
    Print(String),
    RecoverResource(String),
    RemoveCard(String),
    RemoveHistoryEntry(String),
    RemoveHorizon(String),
    RemoveResource(String),
    RemoveResourceTag(String),
    RemoveUserdata(String),
    SearchResources {
        query: String,
        resource_tag_filters: Option<Vec<ResourceTagFilter>>,
        proximity_distance_threshold: Option<f32>,
        proximity_limit: Option<i64>,
    },
    UpdateCardData(String, Vec<u8>),
    UpdateCardDimensions(String, i64, i64, i32, i32),
    UpdateCardResourceID(String, String),
    UpdateCardStackingOrder(String),
    UpdateHistoryEntry(HistoryEntry),
    UpdateHorizon(Horizon),
    UpdateResourceMetadata(ResourceMetadata),
}
